### ISSUE TITLE
eglot support

### ISSUE THREAD

**Issue by appetrosyan** [nilclass/slint-mode#1]
This is probably outside the scope, but `eglot` is built-in, `lsp-mode` is not. 

So would it be reasonable to convert `lsp-mode` into a soft dependency and offer `eglot` support instead.

**Comment by nilclass** [comment]
That does sound reasonable to me. I'm not very familiar with `eglot`, but this might just be the time to change that. I'll look into it and see what I find.

**Comment by nilclass** [comment]
@appetrosyan I pushed some changes to the [eglot-support branch](https://github.com/nilclass/slint-mode/tree/eglot-support), care to give it a try?

**Comment by appetrosyan** [comment]
Certainly! I was half expecting this to be a long term issue

**Comment by erickgnavar** [comment]
I tested the branch and it works well, this will be merged into main anytime soon?

**Comment by nilclass** [comment]
@erickgnavar it is merged now.

I was holding off until someone who uses eglot confirms that the changes work, which you just did.
